package com.digdream.androidrubiksolver.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SOLVES.
 */
public class Solve {

    private Long id;
    /** Not-null value. */
    private String type;
    private String upset;
    /** Not-null value. */
    private String time;
    private String solve;
    private java.util.Date date;

    public Solve() {
    }

    public Solve(Long id) {
        this.id = id;
    }

    public Solve(Long id, String type, String upset, String time, String solve, java.util.Date date) {
        this.id = id;
        this.type = type;
        this.upset = upset;
        this.time = time;
        this.solve = solve;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(String type) {
        this.type = type;
    }

    public String getUpset() {
        return upset;
    }

    public void setUpset(String upset) {
        this.upset = upset;
    }

    /** Not-null value. */
    public String getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(String time) {
        this.time = time;
    }

    public String getSolve() {
        return solve;
    }

    public void setSolve(String solve) {
        this.solve = solve;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
